version: '3'

services:
  database:
    command: --innodb-flush-method=fsync --innodb-fast-shutdown=0 --innodb-use-native-aio=0 --explicit_defaults_for_timestamp
    image: mariadb:10.3.32
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./database/data:/var/lib/mysql

  php:
    build:
      context: ./fpm
    depends_on:
      - database
    ports:
      - "9000:9002"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - PHP_IDE_CONFIG=serverName=${COMPOSE_PROJECT_NAME}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=mariadb-10.3.32&charset=utf8mb4
    volumes:
      - ../src:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php
    ports:
      - ${WEB_PORT}:80
